[phases.setup]
nixPkgs = ["python3", "nodejs", "npm"]

[phases.install]
cmds = [
  "echo 'ERROR: This is a monorepo with backend and frontend directories.'",
  "echo 'Please deploy backend and frontend as separate Railway services.'",
  "echo 'Backend service: Set root directory to ./backend'",
  "echo 'Frontend service: Set root directory to ./frontend'",
  "exit 1"
]

[phases.build]
cmds = [
  "echo 'Build should be handled by individual services'",
  "exit 1"
]

[start]
cmd = "echo 'This monorepo requires separate service deployment' && exit 1" 